[auth]
enabled = true
site_url = "https://novopixvb.vercel.app"
additional_redirect_urls = ["http://localhost:5173/*"]
[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
