// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rkkmtdpgrvtbotvypysq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJra210ZHBncnZ0Ym90dnlweXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2OTM5MzAsImV4cCI6MjA5NzI2OTkzMH0.tVKWB4t9NrVIurX1LZ8FBvkA_iQCvkK0Ge_gFetV6_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);